/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gym;

import java.util.ArrayList;
import java.util.ListIterator;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author LENOVO
 */

//ArrayList to stor data on it.
public class Administrator_form extends javax.swing.JFrame {
ArrayList<Member> members = new ArrayList<Member>();
ArrayList<Trainer> trainers = new ArrayList<Trainer>();
ArrayList<Class> classes = new ArrayList<Class>();

ArrayList<Dates> dates1 = new ArrayList<Dates>();
ArrayList<Dates> dates2 = new ArrayList<Dates>();
ArrayList<Dates> dates3 = new ArrayList<Dates>();


//Function that take panel name as parameter to make it visible and hide another panels
public void switchpanel(JPanel panel)
{
    jLayeredPane1.removeAll();
    jLayeredPane1.add(panel);
    jLayeredPane1.repaint();
    jLayeredPane1.revalidate();
}
    /**
     * Creates new form Administrator_form
     */
    public Administrator_form() {
        
//Start Set some data to be found when use program
        trainers.add(new Trainer(20200, 35, "Tamer", "Male"));
        trainers.add(new Trainer(20201, 32, "Adham", "Male"));
        trainers.add(new Trainer(20202, 30, "Esam", "Male"));

        dates1.add(new Dates("Sunday",1));
        dates1.add(new Dates("Monday",2));
        dates1.add(new Dates("Monday",3));
        
        dates2.add(new Dates("Tuesday",2));
        dates2.add(new Dates("Saturday",5));
        dates2.add(new Dates("Monday",12));
        
        dates3.add(new Dates("Tuesday",11));
        dates3.add(new Dates("Saturday",7));
        dates3.add(new Dates("Friday",9));
        
        trainers.get(0).setDates(dates1);
        trainers.get(1).setDates(dates2);
        trainers.get(2).setDates(dates3);

        members.add(new Member(201917000, 10, "PAY", 50, 20, "Abdo", "Male"));
        members.add(new Member(201917001, 20, "month-by-mont", 51, 20, "Ahmed", "Male"));
        members.add(new Member(201917002, 30, "Term", 55, 20, "Sara", "Female"));
        
        classes.add(new Class("Yoga", "keabing you  calm", 20200, 10, "Sunday", 1, 5));
        classes.add(new Class("weight lifting", "make your body better", 20201, 20, "Monday", 2, 5));
        classes.add(new Class("Cardio Box", "hvhjbjk", 20202, 30, "Monday", 3, 5));
//End Set some data to be found when use program
        
        // Hide all panels and show stsrt panel when form open.       
        initComponents();
        switchpanel(start_Panel);
        
/*Start Fill comboboxes with data when program run //////////////////////////////////////////////////////////////////*/
          if (edit_trainer_id_ComboBox.getItemCount() == 0) {
            for (int i = 0; i < trainers.size(); i++) {
                edit_trainer_id_ComboBox.addItem(Integer.toString(trainers.get(i).getId()));
            } 
        }
        /**************/
        delete_trainer_id_ComboBox.removeAllItems();
        for (int i = 0; i < trainers.size(); i++) {
           delete_trainer_id_ComboBox.addItem(Integer.toString(trainers.get(i).getId()));
        }  
        /**************/
        open_class_trainer_id_ComboBox.removeAllItems();
        for (int i = 0; i < trainers.size(); i++) {
           open_class_trainer_id_ComboBox.addItem(Integer.toString(trainers.get(i).getId()));
        }
        /**************/
        delete_class_id_ComboBox1.removeAllItems();
        for (int i = 0; i < classes.size(); i++) {
            delete_class_id_ComboBox1.addItem(Integer.toString(classes.get(i).getClass_id()));
        }
        /**************/
        if (edit_class_id_ComboBox.getItemCount() == 0 && edit_class_trainer_id_ComboBox1.getItemCount() == 0) {
            for (int i = 0; i < classes.size(); i++) {
               edit_class_id_ComboBox.addItem(Integer.toString(classes.get(i).getClass_id()));
            }

             for (int i = 0; i < trainers.size(); i++) {
               edit_class_trainer_id_ComboBox1.addItem(Integer.toString(trainers.get(i).getId()));
            }
        }
        /*End Fill comboboxes with data when program run ////////////////////////////////////////////////////////////////////*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        Add_trainer_Button = new javax.swing.JButton();
        Edit_trainer_Button = new javax.swing.JButton();
        Delete_trainer_Button = new javax.swing.JButton();
        Open_class_Button = new javax.swing.JButton();
        Edit_class_Button = new javax.swing.JButton();
        Delete_class_Button = new javax.swing.JButton();
        members_membership_Button = new javax.swing.JButton();
        member_class_Button = new javax.swing.JButton();
        memebers_info_Button = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        start_Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        add_trainer_Panel = new javax.swing.JPanel();
        id_Label = new javax.swing.JLabel();
        add_trainer_id_TextField = new javax.swing.JTextField();
        name_Label = new javax.swing.JLabel();
        add_trainer_name_TextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        add_trainer_age_TextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        add_trainer_gender_ComboBox = new javax.swing.JComboBox<>();
        add_trainer_Button = new javax.swing.JButton();
        edit_trainer_Panel = new javax.swing.JPanel();
        edit_trainer_Label = new javax.swing.JLabel();
        edit_trainer_id_ComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        edit_trainer_name_TextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        edit_trainer_age_TextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        edit_trainer_gender_ComboBox = new javax.swing.JComboBox<>();
        edit_trainer_Button = new javax.swing.JButton();
        edit_trainer_gender_Label = new javax.swing.JLabel();
        delete_trainer_Panel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        delete_trainer_Button = new javax.swing.JButton();
        delete_trainer_id_ComboBox = new javax.swing.JComboBox<>();
        open_class_Panel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        open_class_id_TextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        open_class_day_ComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        open_class_time_ComboBox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        open_class_des_TextArea = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        open_class_type_ComboBox = new javax.swing.JComboBox<>();
        open_class_open_Button = new javax.swing.JButton();
        open_class_trainer_id_ComboBox = new javax.swing.JComboBox<>();
        edit_class_Panel = new javax.swing.JPanel();
        edit_class_day_ComboBox1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        edit_class_des_TextArea1 = new javax.swing.JTextArea();
        edit_class_time_ComboBox1 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        edit_class_type_ComboBox1 = new javax.swing.JComboBox<>();
        edit_class_open_Btn = new javax.swing.JButton();
        edit_class_trainer_id_ComboBox1 = new javax.swing.JComboBox<>();
        edit_class_id_ComboBox = new javax.swing.JComboBox<>();
        edit_class_trainer_id_Label = new javax.swing.JLabel();
        edit_class_day_Label = new javax.swing.JLabel();
        edit_class_time_Label = new javax.swing.JLabel();
        edit_class_type_Label = new javax.swing.JLabel();
        delete_class_Panel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        delete_class_Button1 = new javax.swing.JButton();
        delete_class_id_ComboBox1 = new javax.swing.JComboBox<>();
        memeber_membership_Panel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        m_ship_Table = new javax.swing.JTable();
        member_class_Panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        member_class_Table = new javax.swing.JTable();
        members_info_Panel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        members_info_Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 150));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 781, Short.MAX_VALUE)
        );

        menuPanel.setBackground(new java.awt.Color(23, 21, 32));

        Add_trainer_Button.setBackground(new java.awt.Color(0, 0, 0));
        Add_trainer_Button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Add_trainer_Button.setForeground(new java.awt.Color(255, 255, 255));
        Add_trainer_Button.setText("Add Trainer");
        Add_trainer_Button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Add_trainer_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add_trainer_Button.setFocusable(false);
        Add_trainer_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_trainer_ButtonActionPerformed(evt);
            }
        });

        Edit_trainer_Button.setBackground(new java.awt.Color(0, 0, 0));
        Edit_trainer_Button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Edit_trainer_Button.setForeground(new java.awt.Color(255, 255, 255));
        Edit_trainer_Button.setText("Edit Trainer");
        Edit_trainer_Button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Edit_trainer_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Edit_trainer_Button.setFocusable(false);
        Edit_trainer_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_trainer_ButtonActionPerformed(evt);
            }
        });

        Delete_trainer_Button.setBackground(new java.awt.Color(0, 0, 0));
        Delete_trainer_Button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Delete_trainer_Button.setForeground(new java.awt.Color(255, 255, 255));
        Delete_trainer_Button.setText("Delete Trainer");
        Delete_trainer_Button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Delete_trainer_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete_trainer_Button.setFocusable(false);
        Delete_trainer_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_trainer_ButtonActionPerformed(evt);
            }
        });

        Open_class_Button.setBackground(new java.awt.Color(0, 0, 0));
        Open_class_Button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Open_class_Button.setForeground(new java.awt.Color(255, 255, 255));
        Open_class_Button.setText("Open Class");
        Open_class_Button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Open_class_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Open_class_Button.setFocusable(false);
        Open_class_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Open_class_ButtonActionPerformed(evt);
            }
        });

        Edit_class_Button.setBackground(new java.awt.Color(0, 0, 0));
        Edit_class_Button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Edit_class_Button.setForeground(new java.awt.Color(255, 255, 255));
        Edit_class_Button.setText("Edit Class");
        Edit_class_Button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Edit_class_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Edit_class_Button.setFocusable(false);
        Edit_class_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_class_ButtonActionPerformed(evt);
            }
        });

        Delete_class_Button.setBackground(new java.awt.Color(0, 0, 0));
        Delete_class_Button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Delete_class_Button.setForeground(new java.awt.Color(255, 255, 255));
        Delete_class_Button.setText("Delete Class");
        Delete_class_Button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Delete_class_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete_class_Button.setFocusable(false);
        Delete_class_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_class_ButtonActionPerformed(evt);
            }
        });

        members_membership_Button.setBackground(new java.awt.Color(0, 0, 0));
        members_membership_Button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        members_membership_Button.setForeground(new java.awt.Color(255, 255, 255));
        members_membership_Button.setText("View members under a specific type of membership");
        members_membership_Button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        members_membership_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        members_membership_Button.setFocusable(false);
        members_membership_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                members_membership_ButtonActionPerformed(evt);
            }
        });

        member_class_Button.setBackground(new java.awt.Color(0, 0, 0));
        member_class_Button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        member_class_Button.setForeground(new java.awt.Color(255, 255, 255));
        member_class_Button.setText("View members in a specific class");
        member_class_Button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        member_class_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        member_class_Button.setFocusable(false);
        member_class_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                member_class_ButtonActionPerformed(evt);
            }
        });

        memebers_info_Button.setBackground(new java.awt.Color(0, 0, 0));
        memebers_info_Button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        memebers_info_Button.setForeground(new java.awt.Color(255, 255, 255));
        memebers_info_Button.setText("View all members info");
        memebers_info_Button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        memebers_info_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        memebers_info_Button.setFocusable(false);
        memebers_info_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memebers_info_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Add_trainer_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Edit_trainer_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Delete_trainer_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Open_class_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Edit_class_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Delete_class_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addComponent(memebers_info_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(members_membership_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(member_class_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(Add_trainer_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Edit_trainer_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Delete_trainer_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Open_class_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Edit_class_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Delete_class_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(members_membership_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(member_class_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(memebers_info_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));

        start_Panel.setBackground(new java.awt.Color(255, 255, 255));
        start_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel1.setText("Welcome Administrator");
        start_Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 298, -1, -1));

        add_trainer_Panel.setBackground(new java.awt.Color(255, 255, 255));
        add_trainer_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id_Label.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        id_Label.setText("ID ");
        add_trainer_Panel.add(id_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 92, 60));

        add_trainer_id_TextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add_trainer_id_TextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add_trainer_Panel.add(add_trainer_id_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 291, 36));

        name_Label.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        name_Label.setText("Name");
        add_trainer_Panel.add(name_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        add_trainer_name_TextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add_trainer_Panel.add(add_trainer_name_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 291, 35));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Age");
        add_trainer_Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 92, -1));

        add_trainer_age_TextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add_trainer_Panel.add(add_trainer_age_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 291, 35));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Gender");
        add_trainer_Panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, -1, -1));

        add_trainer_gender_ComboBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        add_trainer_gender_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        add_trainer_Panel.add(add_trainer_gender_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 291, 44));

        add_trainer_Button.setBackground(new java.awt.Color(205, 92, 92));
        add_trainer_Button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        add_trainer_Button.setForeground(new java.awt.Color(255, 255, 255));
        add_trainer_Button.setText("Add");
        add_trainer_Button.setBorder(null);
        add_trainer_Button.setBorderPainted(false);
        add_trainer_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_trainer_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_trainer_ButtonActionPerformed(evt);
            }
        });
        add_trainer_Panel.add(add_trainer_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, 226, 40));

        edit_trainer_Panel.setBackground(new java.awt.Color(255, 255, 255));
        edit_trainer_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edit_trainer_Label.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        edit_trainer_Label.setText("ID");
        edit_trainer_Panel.add(edit_trainer_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        edit_trainer_id_ComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edit_trainer_id_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_trainer_id_ComboBoxActionPerformed(evt);
            }
        });
        edit_trainer_Panel.add(edit_trainer_id_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 314, 44));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("Name");
        edit_trainer_Panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        edit_trainer_name_TextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edit_trainer_Panel.add(edit_trainer_name_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 314, 44));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("Age");
        edit_trainer_Panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 92, -1));

        edit_trainer_age_TextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edit_trainer_Panel.add(edit_trainer_age_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 314, 44));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setText("Gender");
        edit_trainer_Panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, -1));

        edit_trainer_gender_ComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edit_trainer_gender_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        edit_trainer_Panel.add(edit_trainer_gender_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 314, 44));

        edit_trainer_Button.setBackground(new java.awt.Color(205, 92, 92));
        edit_trainer_Button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edit_trainer_Button.setForeground(new java.awt.Color(255, 255, 255));
        edit_trainer_Button.setText("Edit");
        edit_trainer_Button.setBorder(null);
        edit_trainer_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit_trainer_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_trainer_ButtonActionPerformed(evt);
            }
        });
        edit_trainer_Panel.add(edit_trainer_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 570, 255, 49));

        edit_trainer_gender_Label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        edit_trainer_gender_Label.setForeground(new java.awt.Color(204, 0, 51));
        edit_trainer_Panel.add(edit_trainer_gender_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 310, 20));

        delete_trainer_Panel.setBackground(new java.awt.Color(255, 255, 255));
        delete_trainer_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Choose id of trainer that you want to delete");
        delete_trainer_Panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        delete_trainer_Button.setBackground(new java.awt.Color(205, 92, 92));
        delete_trainer_Button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        delete_trainer_Button.setForeground(new java.awt.Color(255, 255, 255));
        delete_trainer_Button.setText("Delete");
        delete_trainer_Button.setBorder(null);
        delete_trainer_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_trainer_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_trainer_ButtonActionPerformed(evt);
            }
        });
        delete_trainer_Panel.add(delete_trainer_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 350, 43));

        delete_trainer_id_ComboBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        delete_trainer_Panel.add(delete_trainer_id_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 351, 44));

        open_class_Panel.setBackground(new java.awt.Color(255, 255, 255));
        open_class_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setText("Class ID");
        open_class_Panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        open_class_id_TextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        open_class_Panel.add(open_class_id_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 314, 44));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setText("Trainer ID");
        open_class_Panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel10.setText("Day");
        open_class_Panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        open_class_day_ComboBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        open_class_day_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saturday", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday" }));
        open_class_Panel.add(open_class_day_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 314, 44));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel11.setText("Time");
        open_class_Panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        open_class_time_ComboBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        open_class_time_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        open_class_Panel.add(open_class_time_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 314, 44));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel12.setText("Description");
        open_class_Panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        open_class_des_TextArea.setColumns(20);
        open_class_des_TextArea.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        open_class_des_TextArea.setRows(5);
        jScrollPane1.setViewportView(open_class_des_TextArea);

        open_class_Panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 314, 113));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel13.setText("Type");
        open_class_Panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, -1, -1));

        open_class_type_ComboBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        open_class_type_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YOGA", "FULL BODY FUSION", "CIRCUIT TRAINING", "HIIT", "WATER AEROBICS", "CYCLING", "BOOTCAMP", "ZUMBA", "Zumba Gold", "Family Zumba", "ATHLETIC CONDITIONING", "KICKBOXING", "Chair Yoga", "Core Strength", "Cardio Box", " " }));
        open_class_Panel.add(open_class_type_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 314, 44));

        open_class_open_Button.setBackground(new java.awt.Color(205, 92, 92));
        open_class_open_Button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        open_class_open_Button.setForeground(new java.awt.Color(255, 255, 255));
        open_class_open_Button.setText("Open");
        open_class_open_Button.setBorder(null);
        open_class_open_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        open_class_open_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_class_open_ButtonActionPerformed(evt);
            }
        });
        open_class_Panel.add(open_class_open_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 630, 209, 44));

        open_class_trainer_id_ComboBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        open_class_Panel.add(open_class_trainer_id_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 314, 44));

        edit_class_Panel.setBackground(new java.awt.Color(255, 255, 255));
        edit_class_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edit_class_day_ComboBox1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edit_class_day_ComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saturday", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday" }));
        edit_class_Panel.add(edit_class_day_ComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 314, 44));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel15.setText("Class ID");
        edit_class_Panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel17.setText("Trainer ID");
        edit_class_Panel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel18.setText("Description");
        edit_class_Panel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel19.setText("Day");
        edit_class_Panel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        edit_class_des_TextArea1.setColumns(20);
        edit_class_des_TextArea1.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        edit_class_des_TextArea1.setRows(5);
        jScrollPane5.setViewportView(edit_class_des_TextArea1);

        edit_class_Panel.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 503, 314, 80));

        edit_class_time_ComboBox1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edit_class_time_ComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        edit_class_Panel.add(edit_class_time_ComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 314, 44));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel20.setText("Time");
        edit_class_Panel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel21.setText("Type");
        edit_class_Panel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, -1, -1));

        edit_class_type_ComboBox1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edit_class_type_ComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YOGA", "FULL BODY FUSION", "CIRCUIT TRAINING", "HIIT", "WATER AEROBICS", "CYCLING", "BOOTCAMP", "ZUMBA", "Zumba Gold", "Family Zumba", "ATHLETIC CONDITIONING", "KICKBOXING", "Chair Yoga", "Core Strength", "Cardio Box", " " }));
        edit_class_Panel.add(edit_class_type_ComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 314, 44));

        edit_class_open_Btn.setBackground(new java.awt.Color(205, 92, 92));
        edit_class_open_Btn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edit_class_open_Btn.setForeground(new java.awt.Color(255, 255, 255));
        edit_class_open_Btn.setText("Edit");
        edit_class_open_Btn.setBorder(null);
        edit_class_open_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit_class_open_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_class_open_BtnActionPerformed(evt);
            }
        });
        edit_class_Panel.add(edit_class_open_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 660, 209, 44));

        edit_class_trainer_id_ComboBox1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edit_class_Panel.add(edit_class_trainer_id_ComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 314, 44));

        edit_class_id_ComboBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edit_class_id_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_class_id_ComboBoxActionPerformed(evt);
            }
        });
        edit_class_Panel.add(edit_class_id_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 314, 44));

        edit_class_trainer_id_Label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        edit_class_trainer_id_Label.setForeground(new java.awt.Color(204, 0, 51));
        edit_class_Panel.add(edit_class_trainer_id_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 310, 20));

        edit_class_day_Label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        edit_class_day_Label.setForeground(new java.awt.Color(204, 0, 51));
        edit_class_Panel.add(edit_class_day_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 310, 20));

        edit_class_time_Label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        edit_class_time_Label.setForeground(new java.awt.Color(204, 0, 51));
        edit_class_Panel.add(edit_class_time_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 310, 20));

        edit_class_type_Label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        edit_class_type_Label.setForeground(new java.awt.Color(204, 0, 51));
        edit_class_Panel.add(edit_class_type_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 310, 20));

        delete_class_Panel.setBackground(new java.awt.Color(255, 255, 255));
        delete_class_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Choose id of class that you want to delete");
        delete_class_Panel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        delete_class_Button1.setBackground(new java.awt.Color(205, 92, 92));
        delete_class_Button1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        delete_class_Button1.setForeground(new java.awt.Color(255, 255, 255));
        delete_class_Button1.setText("Delete");
        delete_class_Button1.setBorder(null);
        delete_class_Button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_class_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_class_Button1ActionPerformed(evt);
            }
        });
        delete_class_Panel.add(delete_class_Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 351, 43));

        delete_class_id_ComboBox1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        delete_class_Panel.add(delete_class_id_ComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 351, 44));

        memeber_membership_Panel.setBackground(new java.awt.Color(255, 255, 255));
        memeber_membership_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        m_ship_Table.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        m_ship_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member_ID", "Membership"
            }
        ));
        jScrollPane3.setViewportView(m_ship_Table);

        memeber_membership_Panel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 13, 920, 750));

        member_class_Panel.setBackground(new java.awt.Color(255, 255, 255));
        member_class_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        member_class_Table.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        member_class_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member_ID", "Class_ID"
            }
        ));
        jScrollPane2.setViewportView(member_class_Table);

        member_class_Panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 13, 920, 750));

        members_info_Panel.setBackground(new java.awt.Color(255, 255, 255));
        members_info_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        members_info_Table.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        members_info_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mmeber_ID", "Name", "Age", "Gender", "Ttrainer_ID", "Class_ID", "Membership"
            }
        ));
        jScrollPane4.setViewportView(members_info_Table);

        members_info_Panel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 13, 920, 750));

        jLayeredPane1.setLayer(start_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(add_trainer_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(edit_trainer_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(delete_trainer_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(open_class_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(edit_class_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(delete_class_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(memeber_membership_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(member_class_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(members_info_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 926, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(start_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(add_trainer_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(edit_trainer_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(delete_trainer_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(open_class_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(edit_class_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(delete_class_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(memeber_membership_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(member_class_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(members_info_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(start_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(add_trainer_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(edit_trainer_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(delete_trainer_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(open_class_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(edit_class_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(delete_class_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(memeber_membership_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(member_class_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(members_info_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_trainer_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_trainer_ButtonActionPerformed
        // TODO add your handling code here:
        switchpanel(add_trainer_Panel); // HIde all panels and show add_trainer_Panel.
    }//GEN-LAST:event_Add_trainer_ButtonActionPerformed

    private void Edit_trainer_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_trainer_ButtonActionPerformed
        // TODO add your handling code here:

         if (edit_trainer_id_ComboBox.getItemCount() == 0) {
            for (int i = 0; i < trainers.size(); i++) {
                edit_trainer_id_ComboBox.addItem(Integer.toString(trainers.get(i).getId()));
            }
        }
         
        switchpanel(edit_trainer_Panel); // HIde all panels and show edit_trainer_Panel. 
    }//GEN-LAST:event_Edit_trainer_ButtonActionPerformed

    private void Delete_trainer_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_trainer_ButtonActionPerformed
        // TODO add your handling code here:
        delete_trainer_id_ComboBox.removeAllItems();
        for (int i = 0; i < trainers.size(); i++) {
           delete_trainer_id_ComboBox.addItem(Integer.toString(trainers.get(i).getId()));
        }
        
        switchpanel(delete_trainer_Panel);  // HIde all panels and show delete_trainer_Panel. 
    }//GEN-LAST:event_Delete_trainer_ButtonActionPerformed

    private void Open_class_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Open_class_ButtonActionPerformed
        // TODO add your handling code here:
        open_class_trainer_id_ComboBox.removeAllItems();
        for (int i = 0; i < trainers.size(); i++) {
           open_class_trainer_id_ComboBox.addItem(Integer.toString(trainers.get(i).getId()));
        }
        
      switchpanel(open_class_Panel);  // HIde all panels and show open_class_Panel. 
    }//GEN-LAST:event_Open_class_ButtonActionPerformed

    private void Delete_class_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_class_ButtonActionPerformed
        // TODO add your handling code here:
        delete_class_id_ComboBox1.removeAllItems();
        for (int i = 0; i < classes.size(); i++) {
            delete_class_id_ComboBox1.addItem(Integer.toString(classes.get(i).getClass_id()));
        }
        switchpanel(delete_class_Panel);  // HIde all panels and show delete_class_Panel. 
    }//GEN-LAST:event_Delete_class_ButtonActionPerformed

    private void add_trainer_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_trainer_ButtonActionPerformed
        // TODO add your handling code here:
        
        //Check if user fill all data or no.
        if (add_trainer_id_TextField.getText().toString().equals("") || add_trainer_name_TextField.getText().toString().equals("") || add_trainer_age_TextField.getText().toString().equals("")) 
        {
            
            JOptionPane.showMessageDialog(this, "Fill all data firist");
            
        } else {
            
            //Start get data from TextFieldes and Comboboxes.
            int id = Integer.parseInt(add_trainer_id_TextField.getText().toString());
            String name = add_trainer_name_TextField.getText().toString();
            int age = Integer.parseInt(add_trainer_age_TextField.getText().toString());
            String gender = add_trainer_gender_ComboBox.getSelectedItem().toString();
            //End get data from TextFieldes and Comboboxes.
            
            //Add new trainer to data.
            trainers.add(new Trainer(id, age, name, gender));

            //Add id of trainer to edit_trainer_id_ComboBox to be able update his data if want.
            edit_trainer_id_ComboBox.addItem(add_trainer_id_TextField.getText().toString());

            //Show message to user to tell him that new trainer added.
            JOptionPane.showMessageDialog(this, ">> Trainer added <<");

            //Start Clear TextFieles after add member.
            add_trainer_id_TextField.setText(null);
            add_trainer_name_TextField.setText(null);
            add_trainer_age_TextField.setText(null);
            //End Clear TextFieles after add member.
        }
      
    }//GEN-LAST:event_add_trainer_ButtonActionPerformed

    private void edit_trainer_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_trainer_ButtonActionPerformed
        // TODO add your handling code here:
        
        //Start get data from TextFieldes and Comboboxes
        int id = Integer.parseInt(edit_trainer_id_ComboBox.getSelectedItem().toString());
        String name = edit_trainer_age_TextField.getText().toString();
        int age = Integer.parseInt(edit_trainer_age_TextField.getText().toString());
        String gender = edit_trainer_gender_ComboBox.getSelectedItem().toString();
        //End get data from TextFieldes and Comboboxes
        
        // Get the index of class to be able to make updta on it.
        int index = -1;
        for (int i = 0; i < trainers.size(); i++) {
            if (trainers.get(i).getId()==id) {
                index=i;
            }
        }
       
        // Reblace old data with updated data.
        trainers.set(index, new Trainer(id, age, name, gender));
        
        //Show message to user to tell him that trainer data updated.
        JOptionPane.showMessageDialog(this, ">> Trainer data updated <<");
        
        //show updated data to user.
        edit_trainer_name_TextField.setText(trainers.get(index).getName());
        edit_trainer_age_TextField.setText(""+trainers.get(index).getAge());
        edit_trainer_gender_Label.setText(trainers.get(index).getGender());
        
    }//GEN-LAST:event_edit_trainer_ButtonActionPerformed

    private void open_class_open_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_class_open_ButtonActionPerformed
        // TODO add your handling code here:
        
         if (open_class_id_TextField.getText().toString().equals("") || open_class_des_TextArea.getText().toString().equals("")) 
        {
            
            JOptionPane.showMessageDialog(this, "Fill all data firist");
            
        } else {
             
            //Start get data from TextFieldes and Comboboxes.
            int class_id = Integer.parseInt(open_class_id_TextField.getText().toString());
            int trainer_id = Integer.parseInt(open_class_trainer_id_ComboBox.getSelectedItem().toString());
            String day = open_class_day_ComboBox.getSelectedItem().toString();
            int time = Integer.parseInt(open_class_time_ComboBox.getSelectedItem().toString());
            String type = open_class_type_ComboBox.getSelectedItem().toString();
            String discription = open_class_des_TextArea.getText().toString();
            //Start get data from TextFieldes and Comboboxes.
            
            //Start check if trainer has class in chossen day and time.
            boolean flage = false;
            int position = 0;
            for (int i = 0; i < trainers.size(); i++) {
                if (trainers.get(i).getId()== trainer_id) {
                    position = i;
                    break;
                }
            }

            ArrayList<Dates> d = new ArrayList<Dates>();
            d = trainers.get(position).getDates();
            for (int j = 0; j < d.size(); j++) {
                if (d.get(j).day.equals(day) && d.get(j).time == time) {
                   flage = true; 
                }
            }
            //End check if trainer has class in chossen day and time.
            
            //If trainer has class it choosen day and time show message to user else add class to data.
            if (flage) {
                JOptionPane.showMessageDialog(this, "Sory this trainer has another class in this day and time \n Choose Another Trainer or Change day or time");
            }
            else{ 
                
            //add day and time to trainer data.
            trainers.get(position).dates.add(new Dates(day,time));
            
            //Add new class to data.
            classes.add(new Class(type, discription, trainer_id, class_id, day, time, 0)); 
            
            //Show message to user to tell him that new class added.
            JOptionPane.showMessageDialog(this, ">> Class opned <<");
            
            //Add id of clss to edit_class_id_ComboBox to be able update data if want.
            edit_class_id_ComboBox.addItem(open_class_id_TextField.getText().toString());
            
            //Start Clear TextFieles after add member.
            open_class_id_TextField.setText(null);
            open_class_des_TextArea.setText(null);
            //End Clear TextFieles after add member.
            }
        }
    }//GEN-LAST:event_open_class_open_ButtonActionPerformed

    private void members_membership_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_members_membership_ButtonActionPerformed
        // TODO add your handling code here:
        
        //Start but data in table.
        DefaultTableModel model = (DefaultTableModel) m_ship_Table.getModel();
        Object rowData[] = new Object[2];
        model.setRowCount(0); //clear table
        for (int i = 0; i < members.size(); i++) {
            rowData[0]=members.get(i).getId();
            rowData[1]= members.get(i).getMembership();
            model.addRow(rowData);   
        }
        //End but data in table.
        
        switchpanel(memeber_membership_Panel);  // HIde all panels and show memeber_membership_Panel.
    }//GEN-LAST:event_members_membership_ButtonActionPerformed

    private void member_class_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_class_ButtonActionPerformed
        // TODO add your handling code here:
        
        //Start but data in table.
        DefaultTableModel model = (DefaultTableModel) member_class_Table.getModel();
        Object rowData[] = new Object[2];
        model.setRowCount(0); //clear table
        for (int i = 0; i < members.size(); i++) {
            rowData[0]=members.get(i).getId();
            rowData[1]= members.get(i).getClass_id();
            model.addRow(rowData);
        }
        //End but data in table.
        
        switchpanel(member_class_Panel);  // HIde all panels and show member_class_Panel.

    }//GEN-LAST:event_member_class_ButtonActionPerformed
       
    private void memebers_info_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memebers_info_ButtonActionPerformed
        // TODO add your handling code here:
        
        //Start but data in table.
        DefaultTableModel model = (DefaultTableModel) members_info_Table.getModel();
        Object rowData[] = new Object[7];
        model.setRowCount(0); //clear table
        for (int i = 0; i < members.size(); i++) {
            rowData[0]=members.get(i).getId();
            rowData[1]=members.get(i).getName();
            rowData[2]=members.get(i).getAge();
            rowData[3]=members.get(i).getGender();
            rowData[4]=members.get(i).getTrainer_id();
            rowData[5]=members.get(i).getClass_id();
            rowData[6]= members.get(i).getMembership();
            model.addRow(rowData);
        }
        //End but data in table.
        
        switchpanel(members_info_Panel);   // HIde all panels and show members_info_Panel.  
    }//GEN-LAST:event_memebers_info_ButtonActionPerformed

    private void delete_trainer_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_trainer_ButtonActionPerformed
        // TODO add your handling code here:
        
        //Get id of trainer that will delete.
        int id = Integer.parseInt(delete_trainer_id_ComboBox.getSelectedItem().toString());
        
        //Get index of member that will be deleted .
        int index = -1;
        for (int i = 0; i < trainers.size(); i++) {
            if(id==trainers.get(i).getId())
            {
            index = i;
            } 
        }
        
        //Delete id of deleted trainer from edit_trainer_id_ComboBox.
        edit_trainer_id_ComboBox.removeItem(delete_trainer_id_ComboBox.getSelectedItem().toString());
        
        //Delete trainer from data by using his index.
        trainers.remove(index);
        
        /************************Update comboBox data after delete class**************************/
        delete_trainer_id_ComboBox.removeAllItems();
        for (int i = 0; i < trainers.size(); i++) {
            delete_trainer_id_ComboBox.addItem(Integer.toString(trainers.get(i).getId()));
        }
        switchpanel(delete_trainer_Panel);
        /****************************************************************************************/
    }//GEN-LAST:event_delete_trainer_ButtonActionPerformed

    private void delete_class_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_class_Button1ActionPerformed
        // TODO add your handling code here:

        //Get id of class that will delete.
        int id = Integer.parseInt(delete_class_id_ComboBox1.getSelectedItem().toString());
        
        //Get index of member that will be deleted .
        int index = -1;
        for (int i = 0; i < classes.size(); i++) {
            if(id==classes.get(i).getClass_id())
            {
                index = i;
            }  
        }
        
        //Delete id of deleted class from edit_class_id_ComboBox.
        edit_class_id_ComboBox.removeItem(delete_class_id_ComboBox1.getSelectedItem().toString());

        //Delete class from data by using his index.
        classes.remove(index);
        
        /************************Update comboBox data after delete class**************************/
        delete_class_id_ComboBox1.removeAllItems();
        for (int i = 0; i < classes.size(); i++) {
            delete_class_id_ComboBox1.addItem(Integer.toString(classes.get(i).getClass_id()));
        }
        switchpanel(delete_class_Panel);
        /****************************************************************************************/
    }//GEN-LAST:event_delete_class_Button1ActionPerformed
    
    private void Edit_class_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_class_ButtonActionPerformed
        // TODO add your handling code here:

    if (edit_class_id_ComboBox.getItemCount() == 0 && edit_class_trainer_id_ComboBox1.getItemCount() == 0) {
         for (int i = 0; i < classes.size(); i++) {
           edit_class_id_ComboBox.addItem(Integer.toString(classes.get(i).getClass_id()));
        }
         

         for (int i = 0; i < trainers.size(); i++) {
           edit_class_trainer_id_ComboBox1.addItem(Integer.toString(trainers.get(i).getId()));
        }
    }
    
       switchpanel(edit_class_Panel); // HIde all panels and show edit_class_Panel.
        
    }//GEN-LAST:event_Edit_class_ButtonActionPerformed

    private void edit_class_open_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_class_open_BtnActionPerformed
        // TODO add your handling code here: 
        
        //Start get data from TextFieldes and Comboboxes
        int class_id = Integer.parseInt(edit_class_id_ComboBox.getSelectedItem().toString());
        int trainer_id = Integer.parseInt(edit_class_trainer_id_ComboBox1.getSelectedItem().toString());
        String day = edit_class_day_ComboBox1.getSelectedItem().toString();
        int time = Integer.parseInt(edit_class_time_ComboBox1.getSelectedItem().toString());
        String type = edit_class_type_ComboBox1.getSelectedItem().toString();
        String discription = edit_class_des_TextArea1.getText().toString();
        //Start get data from TextFieldes and Comboboxes
        
        // Get the index of class to be able to make updta on it.
         int index = -1;
        for (int i = 0; i < classes.size(); i++) {
            if (classes.get(i).getClass_id() == class_id) {
                index=i;
            }
        } 
        
        // Reblace old data with updated data.
        classes.set(index, new Class(type, discription, trainer_id, class_id, day, time, classes.get(index).getNum_of_members()));
        
        //Show message to user to tell him that class data updated.
        JOptionPane.showMessageDialog(this, ">> Class data edted <<");
        
        //show updated data to user.
        edit_class_trainer_id_Label.setText(""+classes.get(index).getTrainer_id());
        edit_class_day_Label.setText(classes.get(index).getDay());
        edit_class_time_Label.setText(""+classes.get(index).getTime());
        edit_class_type_Label.setText(classes.get(index).getType());
        edit_class_des_TextArea1.setText(classes.get(index).getDescription());
        
    }//GEN-LAST:event_edit_class_open_BtnActionPerformed

    private void edit_trainer_id_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_trainer_id_ComboBoxActionPerformed
        // TODO add your handling code here:
        
        //This event to show data of selected trainer before edit it.
        
        Object obj = evt.getSource();
        if(obj == edit_trainer_id_ComboBox)
        {
            int id = Integer.parseInt(edit_trainer_id_ComboBox.getSelectedItem().toString());
            int index = -1;
            for (int i = 0; i < trainers.size(); i++) {
                if (trainers.get(i).getId() == id) {
                    index=i;
                    break;
                }
            }
            
            edit_trainer_name_TextField.setText(trainers.get(index).getName());
            edit_trainer_age_TextField.setText(""+trainers.get(index).getAge());
            edit_trainer_gender_Label.setText(trainers.get(index).getGender());
        }
    }//GEN-LAST:event_edit_trainer_id_ComboBoxActionPerformed

    private void edit_class_id_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_class_id_ComboBoxActionPerformed
        // TODO add your handling code here:
        
        //This event to show data of selected class before edit it.
        
        Object obj = evt.getSource();
        if(obj == edit_class_id_ComboBox)
        {
            int id = Integer.parseInt(edit_class_id_ComboBox.getSelectedItem().toString());
            int index = -1;
            for (int i = 0; i < classes.size(); i++) {
                if (classes.get(i).getClass_id() == id) {
                    index=i;
                    break;
                }
            }
            edit_class_trainer_id_Label.setText(""+classes.get(index).getTrainer_id());
            edit_class_day_Label.setText(classes.get(index).getDay());
            edit_class_time_Label.setText(""+classes.get(index).getTime());
            edit_class_type_Label.setText(classes.get(index).getType());
            edit_class_des_TextArea1.setText(classes.get(index).getDescription());

        }
    }//GEN-LAST:event_edit_class_id_ComboBoxActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrator_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrator_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrator_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrator_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrator_form().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_trainer_Button;
    private javax.swing.JButton Delete_class_Button;
    private javax.swing.JButton Delete_trainer_Button;
    private javax.swing.JButton Edit_class_Button;
    private javax.swing.JButton Edit_trainer_Button;
    private javax.swing.JButton Open_class_Button;
    private javax.swing.JButton add_trainer_Button;
    private javax.swing.JPanel add_trainer_Panel;
    private javax.swing.JTextField add_trainer_age_TextField;
    private javax.swing.JComboBox<String> add_trainer_gender_ComboBox;
    private javax.swing.JTextField add_trainer_id_TextField;
    private javax.swing.JTextField add_trainer_name_TextField;
    private javax.swing.JButton delete_class_Button1;
    private javax.swing.JPanel delete_class_Panel;
    private javax.swing.JComboBox<String> delete_class_id_ComboBox1;
    private javax.swing.JButton delete_trainer_Button;
    private javax.swing.JPanel delete_trainer_Panel;
    private javax.swing.JComboBox<String> delete_trainer_id_ComboBox;
    private javax.swing.JPanel edit_class_Panel;
    private javax.swing.JComboBox<String> edit_class_day_ComboBox1;
    private javax.swing.JLabel edit_class_day_Label;
    private javax.swing.JTextArea edit_class_des_TextArea1;
    private javax.swing.JComboBox<String> edit_class_id_ComboBox;
    private javax.swing.JButton edit_class_open_Btn;
    private javax.swing.JComboBox<String> edit_class_time_ComboBox1;
    private javax.swing.JLabel edit_class_time_Label;
    private javax.swing.JComboBox<String> edit_class_trainer_id_ComboBox1;
    private javax.swing.JLabel edit_class_trainer_id_Label;
    private javax.swing.JComboBox<String> edit_class_type_ComboBox1;
    private javax.swing.JLabel edit_class_type_Label;
    private javax.swing.JButton edit_trainer_Button;
    private javax.swing.JLabel edit_trainer_Label;
    private javax.swing.JPanel edit_trainer_Panel;
    private javax.swing.JTextField edit_trainer_age_TextField;
    private javax.swing.JComboBox<String> edit_trainer_gender_ComboBox;
    private javax.swing.JLabel edit_trainer_gender_Label;
    private javax.swing.JComboBox<String> edit_trainer_id_ComboBox;
    private javax.swing.JTextField edit_trainer_name_TextField;
    private javax.swing.JLabel id_Label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable m_ship_Table;
    private javax.swing.JButton member_class_Button;
    private javax.swing.JPanel member_class_Panel;
    private javax.swing.JTable member_class_Table;
    private javax.swing.JPanel members_info_Panel;
    private javax.swing.JTable members_info_Table;
    private javax.swing.JButton members_membership_Button;
    private javax.swing.JPanel memeber_membership_Panel;
    private javax.swing.JButton memebers_info_Button;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel name_Label;
    private javax.swing.JPanel open_class_Panel;
    private javax.swing.JComboBox<String> open_class_day_ComboBox;
    private javax.swing.JTextArea open_class_des_TextArea;
    private javax.swing.JTextField open_class_id_TextField;
    private javax.swing.JButton open_class_open_Button;
    private javax.swing.JComboBox<String> open_class_time_ComboBox;
    private javax.swing.JComboBox<String> open_class_trainer_id_ComboBox;
    private javax.swing.JComboBox<String> open_class_type_ComboBox;
    private javax.swing.JPanel start_Panel;
    // End of variables declaration//GEN-END:variables
}
