/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gym;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class Employee_form extends javax.swing.JFrame {
    
//ArrayList to stor data on it.
    ArrayList<Member> members = new ArrayList<Member>();
    ArrayList<Trainer> trainers = new ArrayList<Trainer>();
    ArrayList<Class> classes = new ArrayList<Class>();

//Function that take panel name as parameter to make it visible and hide another panels
public void switchpanel(JPanel panel)
{
    jLayeredPane1.removeAll();
    jLayeredPane1.add(panel);
    jLayeredPane1.repaint();
    jLayeredPane1.revalidate();
}
    /**
     * Creates new form Employee_form
     */
    public Employee_form() {
        initComponents();
//Start Set some data to be found when use program   
        members.add(new Member(201917000, 10, "PAY", 50, 20, "Abdo", "Male"));
        members.add(new Member(201917001, 20, "month-by-mont", 51, 20, "Ahmed", "Male"));
        members.add(new Member(201917002, 30, "Tem", 55, 20, "Sara", "Female"));

        
        trainers.add(new Trainer(20200, 35, "Tamer", "Male"));
        trainers.add(new Trainer(20201, 32, "Adham", "Male"));
        trainers.add(new Trainer(20202, 30, "Esam", "Male"));
        
        classes.add(new Class("Yoga", "keabing you  calm", 20200, 10, "Sunday", 1, 7));
        classes.add(new Class("weight lifting", "make your body better", 20201, 20, "Monday", 2, 8));
        classes.add(new Class("Cardio Box", "hvhjbjk", 20202, 30, "Monday", 3, 10));  
//End Set some data to be found when use program   

        // Hide all panels and show stsrt panel when form open.
        switchpanel(start_Panel);  

/*Start Fill comboboxes with data when program run //////////////////////////////////////////////////////////////////*/
        if (edit_memeber_id_ComboBox.getItemCount() == 0) {
            for (int i = 0; i < members.size(); i++) {
                edit_member_trainer_id_ComboBox.addItem(Integer.toString(members.get(i).getTrainer_id()));
                edit_member_class_id_ComboBox.addItem(Integer.toString(members.get(i).getClass_id()));
                edit_memeber_id_ComboBox.addItem(Integer.toString(members.get(i).getId()));
         }
        }
        //////////////////////
        add_member_trainer_id_ComboBox.removeAllItems();
         for (int i = 0; i < members.size(); i++) {
           add_member_trainer_id_ComboBox.addItem(Integer.toString(members.get(i).getTrainer_id()));
        }
         
        add_member_class_id_ComboBox.removeAllItems();
         for (int i = 0; i < classes.size(); i++) {
           add_member_class_id_ComboBox.addItem(Integer.toString(classes.get(i).getClass_id()));
        }
        //////////////////////
        delete_member_id_ComboBox.removeAllItems();
        for (int i = 0; i < members.size(); i++) {
           delete_member_id_ComboBox.addItem(Integer.toString(members.get(i).getId()));
        }
/*End Fill comboboxes with data when program run ////////////////////////////////////////////////////////////////////*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        Add_member_Button = new javax.swing.JButton();
        Edit_member_Button = new javax.swing.JButton();
        Delete_member_Button = new javax.swing.JButton();
        members_membership_Button = new javax.swing.JButton();
        member_class_Button = new javax.swing.JButton();
        memebers_info_Button = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        start_Panel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        add_member_Panel = new javax.swing.JPanel();
        id_Label = new javax.swing.JLabel();
        add_member_id_TextField = new javax.swing.JTextField();
        name_Label = new javax.swing.JLabel();
        add_member_name_TextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        add_member_age_TextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        add_member_gender_ComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        add_member_class_id_ComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        add_member_trainer_id_ComboBox = new javax.swing.JComboBox<>();
        add_member_Btn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        add_member_membership_ComboBox = new javax.swing.JComboBox<>();
        edit_member_Panel = new javax.swing.JPanel();
        edit_trainer_Label = new javax.swing.JLabel();
        edit_memeber_id_ComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        edit_memeber_name_TextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        edit_member_age_TextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        edit_memeber_gender_ComboBox = new javax.swing.JComboBox<>();
        edit_member_Btn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        edit_member_class_id_ComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        edit_member_trainer_id_ComboBox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        edit_member_membership_ComboBox = new javax.swing.JComboBox<>();
        edit_memeber_gender_Label = new javax.swing.JLabel();
        edit_member_trainer_id_Label = new javax.swing.JLabel();
        edit_member_class_id_Label = new javax.swing.JLabel();
        edit_member_membership_Label = new javax.swing.JLabel();
        delete_member_Panel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        delete_member_Btn = new javax.swing.JButton();
        delete_member_id_ComboBox = new javax.swing.JComboBox<>();
        memeber_membership_Panel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        m_ship_Table = new javax.swing.JTable();
        member_class_Panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        member_class_Table = new javax.swing.JTable();
        members_info_Panel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        members_info_Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 100));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1345, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 811, Short.MAX_VALUE)
        );

        menuPanel.setBackground(new java.awt.Color(23, 21, 32));

        jLabel14.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Gym Management System");

        Add_member_Button.setBackground(new java.awt.Color(0, 0, 0));
        Add_member_Button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Add_member_Button.setForeground(new java.awt.Color(255, 255, 255));
        Add_member_Button.setText("Add Member");
        Add_member_Button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Add_member_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add_member_Button.setFocusable(false);
        Add_member_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_member_ButtonActionPerformed(evt);
            }
        });

        Edit_member_Button.setBackground(new java.awt.Color(0, 0, 0));
        Edit_member_Button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Edit_member_Button.setForeground(new java.awt.Color(255, 255, 255));
        Edit_member_Button.setText("Edit Member");
        Edit_member_Button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Edit_member_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Edit_member_Button.setFocusable(false);
        Edit_member_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_member_ButtonActionPerformed(evt);
            }
        });

        Delete_member_Button.setBackground(new java.awt.Color(0, 0, 0));
        Delete_member_Button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Delete_member_Button.setForeground(new java.awt.Color(255, 255, 255));
        Delete_member_Button.setText("Delete Member");
        Delete_member_Button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Delete_member_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete_member_Button.setFocusable(false);
        Delete_member_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_member_ButtonActionPerformed(evt);
            }
        });

        members_membership_Button.setBackground(new java.awt.Color(0, 0, 0));
        members_membership_Button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        members_membership_Button.setForeground(new java.awt.Color(255, 255, 255));
        members_membership_Button.setText("View members under a specific type of membership");
        members_membership_Button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        members_membership_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        members_membership_Button.setFocusable(false);
        members_membership_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                members_membership_ButtonActionPerformed(evt);
            }
        });

        member_class_Button.setBackground(new java.awt.Color(0, 0, 0));
        member_class_Button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        member_class_Button.setForeground(new java.awt.Color(255, 255, 255));
        member_class_Button.setText("View members in a specific class");
        member_class_Button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        member_class_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        member_class_Button.setFocusable(false);
        member_class_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                member_class_ButtonActionPerformed(evt);
            }
        });

        memebers_info_Button.setBackground(new java.awt.Color(0, 0, 0));
        memebers_info_Button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        memebers_info_Button.setForeground(new java.awt.Color(255, 255, 255));
        memebers_info_Button.setText("View all members info");
        memebers_info_Button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        memebers_info_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        memebers_info_Button.setFocusable(false);
        memebers_info_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memebers_info_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Add_member_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Edit_member_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Delete_member_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(members_membership_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                    .addComponent(member_class_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(memebers_info_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(89, 89, 89))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel14)
                .addGap(98, 98, 98)
                .addComponent(Add_member_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Edit_member_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Delete_member_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(members_membership_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(member_class_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(memebers_info_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));

        start_Panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Algerian", 0, 48)); // NOI18N
        jLabel13.setText("Welcome Employee");

        javax.swing.GroupLayout start_PanelLayout = new javax.swing.GroupLayout(start_Panel);
        start_Panel.setLayout(start_PanelLayout);
        start_PanelLayout.setHorizontalGroup(
            start_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, start_PanelLayout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(190, 190, 190))
        );
        start_PanelLayout.setVerticalGroup(
            start_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(start_PanelLayout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(jLabel13)
                .addContainerGap(481, Short.MAX_VALUE))
        );

        add_member_Panel.setBackground(new java.awt.Color(255, 255, 255));

        id_Label.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        id_Label.setText("ID ");

        add_member_id_TextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add_member_id_TextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        name_Label.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        name_Label.setText("Name");

        add_member_name_TextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add_member_name_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_member_name_TextFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Age");

        add_member_age_TextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Gender");

        add_member_gender_ComboBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        add_member_gender_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Trainer ID");

        add_member_class_id_ComboBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("Class ID");

        add_member_trainer_id_ComboBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        add_member_Btn.setBackground(new java.awt.Color(205, 92, 92));
        add_member_Btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        add_member_Btn.setForeground(new java.awt.Color(255, 255, 255));
        add_member_Btn.setText("Add");
        add_member_Btn.setBorder(null);
        add_member_Btn.setBorderPainted(false);
        add_member_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_member_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_member_BtnActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel11.setText("Membership");

        add_member_membership_ComboBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        add_member_membership_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PAYG", "Month-By-Month", "Term" }));
        add_member_membership_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_member_membership_ComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout add_member_PanelLayout = new javax.swing.GroupLayout(add_member_Panel);
        add_member_Panel.setLayout(add_member_PanelLayout);
        add_member_PanelLayout.setHorizontalGroup(
            add_member_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_member_PanelLayout.createSequentialGroup()
                .addGroup(add_member_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(add_member_PanelLayout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(add_member_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(add_member_PanelLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(add_member_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_member_PanelLayout.createSequentialGroup()
                                .addComponent(name_Label)
                                .addGap(131, 131, 131)
                                .addComponent(add_member_name_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_member_PanelLayout.createSequentialGroup()
                                .addComponent(id_Label)
                                .addGap(175, 175, 175)
                                .addComponent(add_member_id_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(add_member_PanelLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(131, 131, 131)
                                .addComponent(add_member_age_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(add_member_PanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(108, 108, 108)
                                .addComponent(add_member_gender_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(add_member_PanelLayout.createSequentialGroup()
                                .addGroup(add_member_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel11))
                                .addGap(30, 30, 30)
                                .addGroup(add_member_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(add_member_class_id_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(add_member_membership_ComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(add_member_PanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(62, 62, 62)
                                .addComponent(add_member_trainer_id_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        add_member_PanelLayout.setVerticalGroup(
            add_member_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_member_PanelLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(add_member_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add_member_id_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_Label))
                .addGap(33, 33, 33)
                .addGroup(add_member_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name_Label)
                    .addComponent(add_member_name_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(add_member_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(add_member_age_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(add_member_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(add_member_gender_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(add_member_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(add_member_trainer_id_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(add_member_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(add_member_class_id_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(add_member_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(add_member_membership_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(add_member_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );

        edit_member_Panel.setBackground(new java.awt.Color(255, 255, 255));

        edit_trainer_Label.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        edit_trainer_Label.setText("ID");

        edit_memeber_id_ComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edit_memeber_id_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_memeber_id_ComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("Name");

        edit_memeber_name_TextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setText("Age");

        edit_member_age_TextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setText("Gender");

        edit_memeber_gender_ComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edit_memeber_gender_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        edit_member_Btn.setBackground(new java.awt.Color(205, 92, 92));
        edit_member_Btn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edit_member_Btn.setForeground(new java.awt.Color(255, 255, 255));
        edit_member_Btn.setText("Edit");
        edit_member_Btn.setBorder(null);
        edit_member_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit_member_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_member_BtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setText("Trainer ID");

        edit_member_class_id_ComboBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setText("Class ID");

        edit_member_trainer_id_ComboBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel12.setText("Membership");

        edit_member_membership_ComboBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edit_member_membership_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PAYG", "Month-By-Month", "Term" }));

        edit_memeber_gender_Label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        edit_memeber_gender_Label.setForeground(new java.awt.Color(204, 0, 51));

        edit_member_trainer_id_Label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        edit_member_trainer_id_Label.setForeground(new java.awt.Color(204, 0, 51));

        edit_member_class_id_Label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        edit_member_class_id_Label.setForeground(new java.awt.Color(204, 0, 51));

        edit_member_membership_Label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        edit_member_membership_Label.setForeground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout edit_member_PanelLayout = new javax.swing.GroupLayout(edit_member_Panel);
        edit_member_Panel.setLayout(edit_member_PanelLayout);
        edit_member_PanelLayout.setHorizontalGroup(
            edit_member_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edit_member_PanelLayout.createSequentialGroup()
                .addGroup(edit_member_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(edit_member_PanelLayout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(edit_member_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(edit_member_PanelLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(edit_member_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(edit_member_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(edit_trainer_Label)
                                .addComponent(jLabel5))
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(73, 73, 73)
                        .addGroup(edit_member_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edit_memeber_id_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(edit_memeber_name_TextField)
                            .addComponent(edit_member_age_TextField)
                            .addComponent(edit_memeber_gender_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(edit_member_class_id_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(edit_member_trainer_id_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(edit_member_membership_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(edit_member_class_id_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(edit_member_membership_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(edit_memeber_gender_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edit_member_trainer_id_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        edit_member_PanelLayout.setVerticalGroup(
            edit_member_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edit_member_PanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(edit_member_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(edit_trainer_Label)
                    .addComponent(edit_memeber_id_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(edit_member_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(edit_memeber_name_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(edit_member_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(edit_member_age_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(edit_member_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(edit_memeber_gender_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edit_memeber_gender_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(edit_member_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(edit_member_trainer_id_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(edit_member_trainer_id_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(edit_member_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(edit_member_class_id_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(edit_member_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(edit_member_PanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel12))
                    .addGroup(edit_member_PanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(edit_member_class_id_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edit_member_membership_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(edit_member_membership_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(edit_member_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );

        delete_member_Panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Choose id of memeber that you want to delete");

        delete_member_Btn.setBackground(new java.awt.Color(205, 92, 92));
        delete_member_Btn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        delete_member_Btn.setForeground(new java.awt.Color(255, 255, 255));
        delete_member_Btn.setText("Delete");
        delete_member_Btn.setBorder(null);
        delete_member_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_member_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_member_BtnActionPerformed(evt);
            }
        });

        delete_member_id_ComboBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        delete_member_id_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_member_id_ComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout delete_member_PanelLayout = new javax.swing.GroupLayout(delete_member_Panel);
        delete_member_Panel.setLayout(delete_member_PanelLayout);
        delete_member_PanelLayout.setHorizontalGroup(
            delete_member_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delete_member_PanelLayout.createSequentialGroup()
                .addGroup(delete_member_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(delete_member_PanelLayout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addGroup(delete_member_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(delete_member_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete_member_id_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(delete_member_PanelLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel10)))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        delete_member_PanelLayout.setVerticalGroup(
            delete_member_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delete_member_PanelLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel10)
                .addGap(64, 64, 64)
                .addComponent(delete_member_id_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(delete_member_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(416, Short.MAX_VALUE))
        );

        memeber_membership_Panel.setBackground(new java.awt.Color(255, 255, 255));
        memeber_membership_Panel.setPreferredSize(new java.awt.Dimension(907, 862));

        m_ship_Table.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        m_ship_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member_ID", "Membership"
            }
        ));
        jScrollPane3.setViewportView(m_ship_Table);

        javax.swing.GroupLayout memeber_membership_PanelLayout = new javax.swing.GroupLayout(memeber_membership_Panel);
        memeber_membership_Panel.setLayout(memeber_membership_PanelLayout);
        memeber_membership_PanelLayout.setHorizontalGroup(
            memeber_membership_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
        );
        memeber_membership_PanelLayout.setVerticalGroup(
            memeber_membership_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memeber_membership_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE))
        );

        member_class_Panel.setBackground(new java.awt.Color(255, 255, 255));

        member_class_Table.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        member_class_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member_ID", "Class_ID"
            }
        ));
        jScrollPane2.setViewportView(member_class_Table);

        javax.swing.GroupLayout member_class_PanelLayout = new javax.swing.GroupLayout(member_class_Panel);
        member_class_Panel.setLayout(member_class_PanelLayout);
        member_class_PanelLayout.setHorizontalGroup(
            member_class_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
        );
        member_class_PanelLayout.setVerticalGroup(
            member_class_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(member_class_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE))
        );

        members_info_Panel.setBackground(new java.awt.Color(255, 255, 255));

        members_info_Table.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        members_info_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mmeber_ID", "Name", "Age", "Gender", "Ttrainer_ID", "Class_ID", "Membership"
            }
        ));
        jScrollPane4.setViewportView(members_info_Table);

        javax.swing.GroupLayout members_info_PanelLayout = new javax.swing.GroupLayout(members_info_Panel);
        members_info_Panel.setLayout(members_info_PanelLayout);
        members_info_PanelLayout.setHorizontalGroup(
            members_info_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
        );
        members_info_PanelLayout.setVerticalGroup(
            members_info_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(members_info_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(start_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(add_member_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(edit_member_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(delete_member_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(memeber_membership_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(member_class_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(members_info_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 907, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(start_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(add_member_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(edit_member_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(delete_member_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(memeber_membership_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(member_class_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(members_info_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(start_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(add_member_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(edit_member_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(delete_member_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(memeber_membership_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(member_class_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(members_info_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_member_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_member_ButtonActionPerformed
        // TODO add your handling code here:
       add_member_trainer_id_ComboBox.removeAllItems();
         for (int i = 0; i < members.size(); i++) {
           add_member_trainer_id_ComboBox.addItem(Integer.toString(members.get(i).getTrainer_id()));
        }
         
        add_member_class_id_ComboBox.removeAllItems();
         for (int i = 0; i < classes.size(); i++) {
           add_member_class_id_ComboBox.addItem(Integer.toString(classes.get(i).getClass_id()));
        }
         
       switchpanel(add_member_Panel); // HIde all panels and show add_member_Panel.
        
    }//GEN-LAST:event_Add_member_ButtonActionPerformed

    private void Edit_member_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_member_ButtonActionPerformed
        // TODO add your handling code here:
       
       
       if (edit_memeber_id_ComboBox.getItemCount() == 0) {
            for (int i = 0; i < members.size(); i++) {
              edit_member_trainer_id_ComboBox.addItem(Integer.toString(members.get(i).getTrainer_id()));
              edit_member_class_id_ComboBox.addItem(Integer.toString(members.get(i).getClass_id()));
              edit_memeber_id_ComboBox.addItem(Integer.toString(members.get(i).getId()));
            }
       }  
       switchpanel(edit_member_Panel);  // HIde all panels and show edit_member_Panel.
    }//GEN-LAST:event_Edit_member_ButtonActionPerformed

    private void Delete_member_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_member_ButtonActionPerformed
        // TODO add your handling code here:
        delete_member_id_ComboBox.removeAllItems();
        for (int i = 0; i < members.size(); i++) {
           delete_member_id_ComboBox.addItem(Integer.toString(members.get(i).getId()));
        }
        switchpanel(delete_member_Panel);  // HIde all panels and show delete_member_Panel.
    }//GEN-LAST:event_Delete_member_ButtonActionPerformed

    private void add_member_name_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_member_name_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_member_name_TextFieldActionPerformed

    private void add_member_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_member_BtnActionPerformed
        // TODO add your handling code here:
        
        if (add_member_id_TextField.getText().toString().equals("") || add_member_name_TextField.getText().toString().equals("") || add_member_age_TextField.getText().toString().equals("")) 
        { 
            
            JOptionPane.showMessageDialog(this, "Fill all data firist");
  
        } else {
            
            //Start get data from TextFieldes and Comboboxes
            int id = Integer.parseInt(add_member_id_TextField.getText().toString());
            String name = add_member_name_TextField.getText().toString();
            int age = Integer.parseInt(add_member_age_TextField.getText().toString());
            String gender = add_member_gender_ComboBox.getSelectedItem().toString();
            int trainer_id = Integer.parseInt(add_member_trainer_id_ComboBox.getSelectedItem().toString());
            int class_id = Integer.parseInt((String)add_member_class_id_ComboBox.getSelectedItem().toString());
            String membership = add_member_membership_ComboBox.getSelectedItem().toString();
            //End get data from TextFieldes and Comboboxes

            int num_of_members = 0; // This variable to store on it number of members of class that user choose it.

            int i;
            for (i = 0; i < classes.size(); i++) {
                if(class_id == classes.get(i).getClass_id())
                {
                num_of_members = classes.get(i).getNum_of_members();
                break;
                } 
            }

            // Start Check if number of members of selected class less than 11 add new member else ask user to choose anothe class.
            if(num_of_members < 11)
            {
                //Add new member to data.
                members.add(new Member(trainer_id, class_id, membership, id, age, name, gender));

                // Increment number of member of class that user join it.
                classes.get(i).increment_num_of_members(); 

                //Add id of member to edit_memeber_id_ComboBox to be able update his data if want.
                edit_memeber_id_ComboBox.addItem(add_member_id_TextField.getText().toString());

                //Show message to user to tell him that new member added.
                JOptionPane.showMessageDialog(this, ">> Member added <<");

                //Start Clear TextFieles after add member.
                add_member_id_TextField.setText(null);
                add_member_name_TextField.setText(null);
                add_member_age_TextField.setText(null);
                //End Clear TextFieles after add member.
            }
            else{
                JOptionPane.showMessageDialog(null, "Can't add this memeber to this class.\n please, choose another class");
            }
            // End Check if number of members of selected class less than 11 add new member else ask user to choose anothe class.
        }
        
    }//GEN-LAST:event_add_member_BtnActionPerformed

    private void edit_member_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_member_BtnActionPerformed
        // TODO add your handling code here:
        
        //Start get data from TextFieldes and Comboboxes
        int id = Integer.parseInt(edit_memeber_id_ComboBox.getSelectedItem().toString());
        String name = edit_memeber_name_TextField.getText().toString();
        int age = Integer.parseInt(edit_member_age_TextField.getText().toString());
        String gender = edit_memeber_gender_ComboBox.getSelectedItem().toString();
        int trainer_id = Integer.parseInt(edit_member_trainer_id_ComboBox.getSelectedItem().toString());
        int class_id = Integer.parseInt(edit_member_class_id_ComboBox.getSelectedItem().toString());
        String membership = edit_member_membership_ComboBox.getSelectedItem().toString();
        //End get data from TextFieldes and Comboboxes

        // Get the index of class to be able to make updta on it.
        int index = -1;
        for (int i = 0; i < members.size(); i++) {
            if (members.get(i).getId()==id) {
                index=i;
                break;
            }
        }
        
        // Decrement number of member of class that user leave it.
        for (int i = 0; i < classes.size(); i++) {
            if (classes.get(i).getClass_id() == members.get(index).getClass_id()) {
                classes.get(i).decrement_num_of_members();
                break;
            }
        }
        
        // Increment number of member of class that user join it.
        for (int i = 0; i < classes.size(); i++) {
             if (classes.get(i).getClass_id() == class_id) {
                classes.get(i).increment_num_of_members();
                break;
            }
        }
        
        // Reblace old data with updated data.
        members.set(index, new Member(trainer_id, class_id, membership, id, age, name, gender));
        
        //Show message to user to tell him that trainer data updated.
        JOptionPane.showMessageDialog(this, ">> Member data updated <<");
        
        //show updated data to user.
        edit_memeber_name_TextField.setText(members.get(index).getName());
        edit_member_age_TextField.setText(""+members.get(index).getAge());
        edit_memeber_gender_Label.setText(members.get(index).getGender());
        edit_member_trainer_id_Label.setText(""+members.get(index).getTrainer_id());
        edit_member_class_id_Label.setText(""+members.get(index).getClass_id());
        edit_member_membership_Label.setText(members.get(index).getMembership());  
    }//GEN-LAST:event_edit_member_BtnActionPerformed

    private void delete_member_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_member_BtnActionPerformed
        // TODO add your handling code here:
      
        //Get id of member that will delete.
        int id = Integer.parseInt(delete_member_id_ComboBox.getSelectedItem().toString());
        
        //Get index of member that will be deleted .
        int index = -1;
        for (int i = 0; i < members.size(); i++) {
            if(id==members.get(i).getId())
            {
            index = i;
            break;
            } 
        }
        
        // Decrement number of member of class that user was on it. 
        for (int i = 0; i < classes.size(); i++) {
         if (classes.get(i).getClass_id()== members.get(index).getClass_id()) {
             classes.get(i).decrement_num_of_members();
             break;
         }
        }
        
        //Delete id of deleted member from edit_memeber_id_ComboBox.
        edit_memeber_id_ComboBox.removeItem(delete_member_id_ComboBox.getSelectedItem().toString());
        
        //Delete member from data by using his index.
        members.remove(index);
        
        //Start Update comboBox data after delete class.
        delete_member_id_ComboBox.removeAllItems();
        for (int i = 0; i < members.size(); i++) {
           delete_member_id_ComboBox.addItem(Integer.toString(members.get(i).getId()));
        }
        switchpanel(delete_member_Panel);
        //End Update comboBox data after delete class.
    }//GEN-LAST:event_delete_member_BtnActionPerformed

    private void delete_member_id_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_member_id_ComboBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_delete_member_id_ComboBoxActionPerformed

    private void members_membership_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_members_membership_ButtonActionPerformed
        // TODO add your handling code here:
       
        //Start but data in table.
        DefaultTableModel model = (DefaultTableModel) m_ship_Table.getModel();
        Object rowData[] = new Object[2];
        model.setRowCount(0); //clear table
        for (int i = 0; i < members.size(); i++) {
            rowData[0]=members.get(i).getId();
            rowData[1]= members.get(i).getMembership();
            model.addRow(rowData); 
        }
        //End but data in table.
        
        // HIde all panels and show memeber_membership_Panel.
        switchpanel(memeber_membership_Panel);
    }//GEN-LAST:event_members_membership_ButtonActionPerformed

    private void member_class_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_class_ButtonActionPerformed
        // TODO add your handling code here:
       
        //Start but data in table.
        DefaultTableModel model = (DefaultTableModel) member_class_Table.getModel();
        Object rowData[] = new Object[2];
        model.setRowCount(0); //clear table
        for (int i = 0; i < members.size(); i++) {
            rowData[0]=members.get(i).getId();
            rowData[1]= members.get(i).getClass_id();
            model.addRow(rowData);
        } 
        //End but data in table.
        
        // HIde all panels and show member_class_Panel.
        switchpanel(member_class_Panel);
    }//GEN-LAST:event_member_class_ButtonActionPerformed

    private void memebers_info_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memebers_info_ButtonActionPerformed
        // TODO add your handling code here:
        
        //Start but data in table.
        DefaultTableModel model = (DefaultTableModel) members_info_Table.getModel();
        Object rowData[] = new Object[7];
        model.setRowCount(0); //clear table
        for (int i = 0; i < members.size(); i++) {
            rowData[0]= members.get(i).getId();
            rowData[1]= members.get(i).getName();
            rowData[2]= members.get(i).getAge();
            rowData[3]= members.get(i).getGender();
            rowData[4]= members.get(i).getTrainer_id();
            rowData[5]= members.get(i).getClass_id();
            rowData[6]= members.get(i).getMembership();
            model.addRow(rowData);
        }
        //End but data in table.
        
        // HIde all panels and show members_info_Panel.
        switchpanel(members_info_Panel);
    }//GEN-LAST:event_memebers_info_ButtonActionPerformed

    private void add_member_membership_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_member_membership_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_member_membership_ComboBoxActionPerformed

    private void edit_memeber_id_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_memeber_id_ComboBoxActionPerformed
        // TODO add your handling code here:
        
        //This event to show data of selected member before edit it.
        
        Object obj = evt.getSource();
        if(obj == edit_memeber_id_ComboBox)
        {
            int id = Integer.parseInt(edit_memeber_id_ComboBox.getSelectedItem().toString());
            int index = -1;
            for (int i = 0; i < members.size(); i++) {
                if (members.get(i).getId() == id) {
                    index=i;
                    break;
                }
            }           
           edit_memeber_name_TextField.setText(members.get(index).getName());
           edit_member_age_TextField.setText(""+members.get(index).getAge());
           edit_memeber_gender_Label.setText(members.get(index).getGender());
           edit_member_trainer_id_Label.setText(""+members.get(index).getTrainer_id());
           edit_member_class_id_Label.setText(""+members.get(index).getClass_id());
           edit_member_membership_Label.setText(members.get(index).getMembership());  
        }
        
    }//GEN-LAST:event_edit_memeber_id_ComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_member_Button;
    private javax.swing.JButton Delete_member_Button;
    private javax.swing.JButton Edit_member_Button;
    private javax.swing.JButton add_member_Btn;
    private javax.swing.JPanel add_member_Panel;
    private javax.swing.JTextField add_member_age_TextField;
    private javax.swing.JComboBox<String> add_member_class_id_ComboBox;
    private javax.swing.JComboBox<String> add_member_gender_ComboBox;
    private javax.swing.JTextField add_member_id_TextField;
    private javax.swing.JComboBox<String> add_member_membership_ComboBox;
    private javax.swing.JTextField add_member_name_TextField;
    private javax.swing.JComboBox<String> add_member_trainer_id_ComboBox;
    private javax.swing.JButton delete_member_Btn;
    private javax.swing.JPanel delete_member_Panel;
    private javax.swing.JComboBox<String> delete_member_id_ComboBox;
    private javax.swing.JButton edit_member_Btn;
    private javax.swing.JPanel edit_member_Panel;
    private javax.swing.JTextField edit_member_age_TextField;
    private javax.swing.JComboBox<String> edit_member_class_id_ComboBox;
    private javax.swing.JLabel edit_member_class_id_Label;
    private javax.swing.JComboBox<String> edit_member_membership_ComboBox;
    private javax.swing.JLabel edit_member_membership_Label;
    private javax.swing.JComboBox<String> edit_member_trainer_id_ComboBox;
    private javax.swing.JLabel edit_member_trainer_id_Label;
    private javax.swing.JComboBox<String> edit_memeber_gender_ComboBox;
    private javax.swing.JLabel edit_memeber_gender_Label;
    private javax.swing.JComboBox<String> edit_memeber_id_ComboBox;
    private javax.swing.JTextField edit_memeber_name_TextField;
    private javax.swing.JLabel edit_trainer_Label;
    private javax.swing.JLabel id_Label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable m_ship_Table;
    private javax.swing.JButton member_class_Button;
    private javax.swing.JPanel member_class_Panel;
    private javax.swing.JTable member_class_Table;
    private javax.swing.JPanel members_info_Panel;
    private javax.swing.JTable members_info_Table;
    private javax.swing.JButton members_membership_Button;
    private javax.swing.JPanel memeber_membership_Panel;
    private javax.swing.JButton memebers_info_Button;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel name_Label;
    private javax.swing.JPanel start_Panel;
    // End of variables declaration//GEN-END:variables
}
